# swarm_vars.yml
traefik_acme_email: "rosthanlinux@gmail.com"
base_domain: "nordsh.com"

dashboard: teste1
app_teste: kd

# Você pode adicionar outras configs aqui no futuro, por exemplo:
# traefik_log_level: "INFO"

# --- VARIAVEIS DE SEGURANÇA E REDE ---

# 1. Credenciais do Dashboard Traefik (HTTP Basic Auth)
traefik_username: "rosth"
# O valor abaixo deve ser gerado usando htpasswd -nb admin SUA_SENHA
traefik_hashed_password: "cazia:$$2y$$05$$pHRUFiq0ukqcLIgHKnllIuK5HWG65U5Wz3QfNKyqByuGAMFc/MBZa"

# 2. Faixa de IPs Confiáveis para Proxy/Forwarded Headers
# CRUCIAL: Deve ser o CIDR da sua VPC (10.0.0.0/16) para o NLB funcionar corretamente.
trusted_ip_range: "10.0.0.0/16"